name: 'Generate Fortify tool descriptors'
description: 'Generate Fortify tool descriptors'
author: 'Fortify'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token used to perform GitHub operations'
    required: true
  tool_name:
    description: 'The tool name for which to generate tool definitions.'
    required: true
  tool_repo:
    description: 'The GitHub repository for which to generate tool definitions. Required unless tool_urls is specified.'
    required: false
  tool_urls:
    description: 'JSON string specifying tool versions & URLs for which to generate tool definitions, in the format {"<version>": "<url>", ...}. Required unless tool_repo is specified.'
    required: false
  asset_regex:
    description: 'Optional regular expression to define what releases/assets to include, matching <version without v-prefix>/<asset name>'
    required: false
  sign_key:
    description: 'Base64-encoded RSA signing key, usually provided through GitHub secret'
    required: true
  sign_passphrase:
    description: 'Passphrase for the RSA signing key provided throgh sign_key, usually provided through GitHub secret'
    required: true
  add_semver:
    description: 'Boolean indicating whether semantic versions should be added to the output'
    default: 'false'
    required: false
runs:
  using: node20
  main: 'dist/index.js'
branding:
  icon: 'shield'
  color: 'blue'

