on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write
      
name: Publish tool definitions
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
    - name: Setup
      id: setup
      env:
        CONFIG: >-
          [
             {
                  "tool_name": "fod-uploader",
                  "tool_repo": "fod-dev/fod-uploader-java",
                  "regex": ".*/FodUpload.jar"
              },
              {
                  "tool_name": "fcli",
                  "tool_repo": "fortify/fcli",
                  "regex": ".*/(fcli-linux.tgz|fcli-mac.tgz|fcli-windows.zip)"
              },
              {
                  "tool_name": "bugtracker-utility",
                  "tool_repo": "fortify-ps/FortifyBugTrackerUtility",
                  "regex": ".*/FortifyBugTrackerUtility-.*.zip"
              },
              {
                  "tool_name": "vuln-exporter",
                  "tool_repo": "fortify/FortifyVulnerabilityExporter",
                  "regex": ".*/FortifyVulnerabilityExporter.jar"
              },
              {
                  "tool_name": "debricked-cli",
                  "tool_repo": "debricked/cli",
                  "regex": ".*/cli_.*.tar.gz"
              },
              {
                  "tool_name": "sc-client",
                  "tool_urls": {
                     "23.1.0": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_23.1.0_x64.zip",
                     "22.2.1": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_22.2.1_x64.zip",
                     "22.2.0": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_22.2.0_x64.zip",
                     "22.1.2": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_22.1.2_x64.zip",
                     "22.1.0": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_22.1.0_x64.zip",
                     "21.2.3": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.2.3_x64.zip",
                     "21.2.2": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.2.2_x64.zip",
                     "22.2.0": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.2.0_x64.zip",
                     "21.1.4": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.1.4_x64.zip",
                     "21.1.3": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.1.3_x64.zip",
                     "21.1.2": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.1.2_x64.zip",
                     "20.2.4": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_20.2.4_x64.zip",
                     "20.2.0": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_20.2.0_x64.zip",
                     "20.1.0": "https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_20.1.0_x64.zip"
                  }
               }
          ]
      run: echo "matrix=$(jq -r -c . <<< "$CONFIG")" >> $GITHUB_OUTPUT
    - name: Check
      run: jq . <<< '${{ steps.setup.outputs.matrix }}'
      
  generate-tool-definitions:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v4
    - run: git pull
    - name: Check
      env:
        MATRIX: ${{ toJSON(matrix) }}
        TOOL_NAME: ${{ fromJSON(toJSON(matrix)).tool_name }}
        TOOL_REPO: ${{ fromJSON(toJSON(matrix)).tool_repo }}
        REGEX: ${{ fromJSON(toJSON(matrix)).regex }} 
      run: |
        echo "MATRIX: $(jq -r -c '.' <<< "$MATRIX")"
        echo "TOOL_NAME: [$TOOL_NAME]"
        echo "TOOL_REPO: [$TOOL_REPO]"
        echo "REGEX: [$REGEX]"
    - name: Generate tool definitions
      uses: ./internal/generator
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tool_name: ${{ fromJSON(toJSON(matrix)).tool_name }}
        tool_repo: ${{ fromJSON(toJSON(matrix)).tool_repo }}
        tool_urls: ${{ toJSON(fromJSON(toJSON(matrix)).tool_urls) }}
        regex: ${{ fromJSON(toJSON(matrix)).regex }}
        sign_key: ${{ secrets.SIGN_KEY }}
        sign_passphrase: ${{ secrets.SIGN_PASSPHRASE }}
    - name: Configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@fortify.com
    - name: Commit updates
      run: | 
        git add . && git commit -m "chore: Update ${{ fromJSON(toJSON(matrix)).tool_name }} cache & resources" \
          && git push || \
          echo "No update needed or update failed"
              
        
        
        
        